framework:
    notifier:
        chatter_transports:
        texter_transports:
            twilio: 'twilio://UScdebd366bb9ff20b8ba9bd25daea5fa9:04dcd37eab39d85f4d234736360170a8@default?from=%2B17756557047'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'sms']
            high: ['email', 'sms']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
        
        
